name       : libldac
version    : 2.0.2.31
release    : 1
source     :
    - https://github.com/EHfive/ldacBT/archive/refs/tags/v2.0.2.3.tar.gz : c02998718f9c4620437d7594b4d121b3ab4c5cfeba8d41fa31dd5c71db09edca
    - git|https://android.googlesource.com/platform/external/libldac : platform-tools-31.0.2
homepage   : https://android.googlesource.com/platform/external/libldac
license    : Apache-2.0
component  : multimedia.codecs
summary    : LDAC Bluetooth encoder library
description: |
    LDAC is an audio coding technology developed by Sony that enables the transmission of High Resolution (Hi-Res) Audio content even over a Bluetooth connection. 
setup      : |
    rm -rf libldac
    cp -r $sources/libldac.git libldac
    %patch -p1 < $pkgfiles/ldac-soname-version.patch
    sed -i "s|@SOURCE_VER@|${version/2.0.2./}|" CMakeLists.txt
    %cmake_ninja -DINSTALL_LIBDIR=lib%LIBSUFFIX%
build      : |
    %ninja_build
install    : |
    %ninja_install
